trigger:
- week1

pool: deen

steps:
- task: PowerShell@5
  displayName: 'Running Pipeline Script'
  inputs:
    azureSubscription: 'CloudOps'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: './week1/devops-pipeline-script.sh'
