trigger:
- week1

pool: deen

steps:
- task: AzureCLI@2
  displayName: 'Running Pipeline Script'
  inputs:
    azureSubscription: 'CloudOps'
    scriptType: 'bash'
    workingDirectory: 'scriptPath'
    scriptPath: './devops-pipeline-script.sh'
